// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgbbjvqsscvomyulvbhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnYmJqdnFzc2N2b215dWx2YmhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NTE1NTIsImV4cCI6MjA2NjEyNzU1Mn0.slzjNC-SkIE1yw_6Ipju4Y1CX97BnW6bqhoNLzOx2wk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);